config/routes.rb
Criminaldb::Application.routes.draw do
  resources :criminals
  resources :results
  resources :home
  devise_for :users
  root :to => "results#index"
  match 'criminals/result' => 'callback#process_notification'

end

app/models/criminal.rb
class Criminal < ActiveRecord::Base
  include HTTMultiParty

  # has_many :results, :dependent => :destroy
  after_create :send_to_cf
  attr_accessible :name, :photo
  validates :photo, :presence => true
  mount_uploader :photo, PhotoUploader


  def send_to_cf
    response = Criminal.post('http://api.imgur.com/2/upload', :query => { :key => '3d261fa489c860fcecfa26ae37911f8d', :image => File.new("#{Rails.root}/public#{self.photo}") })
    run = CF::Run.create("lujaw/criminaldb-4", "test#{self.id}", [{"image_url" => response["upload"]["links"]["original"], :meta_data => self.id}])
    end

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :criminal

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/callback_controller.rb
class CallbackController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :process_notification
  def process_notification
    begin
      params[:final_outputs].each do |output|
        @result=Result.new(:criminal_id => params[:meta_data],:name => output["name"] ,:age => output["age"] ,:gender => output["gender"] ,:race => output["race"] ,:eye_color => output["eye_color"] ,:hair_color => output["hair_color"] ,:additional_info => output["additional_info"])
        @result.photo = Criminal.find(params[:meta_data]).photo.to_s
        @result.save
      end
      render :nothing => true, :status => :ok
    rescue Exception => e
      log = "Error msg => " + e.message + "\n" + "Received Data => #{params.inspect}\n" + "Received on => #{Time.now}\n"
      ActiveRecord::Base.logger.info(log)
      ActiveRecord::Base.logger.flush
      render :text => log, :status => 500
    end
  end
end

app/controllers/criminals_controller.rb
class CriminalsController < ApplicationController
  # GET /criminals
  # GET /criminals.json
  helper_method :sort_column , :sort_direction
  def index
    @criminals = Criminal.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @criminals }
    end
  end
  # GET /criminals/1
  # GET /criminals/1.json
  def show
    @criminal = Criminal.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @criminal }
    end
  end
  # GET /criminals/new
  # GET /criminals/new.json
  def new
    @criminal = Criminal.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @criminal }
    end
  end
  # GET /criminals/1/edit
  def edit
    @criminal = Criminal.find(params[:id])
  end
  # POST /criminals
  # POST /criminals.json
  def create
    @criminal = Criminal.new(params[:criminal])
    respond_to do |format|
      if @criminal.save
        @criminal.send_to_cf
        format.html { redirect_to @criminal, notice: 'Photo has been successfully uploaded.'}
        format.json { render json: @criminal, status: :created, location: @criminal }
      else
        format.html { render action: "new" }
        format.json { render json: @criminal.errors, status: :unprocessable_entity }
      end
    end
  end
  # PUT /criminals/1
  # PUT /criminals/1.json
  def update
    @criminal = Criminal.find(params[:id])
    respond_to do |format|
      if @criminal.update_attributes(params[:criminal])
        format.html { redirect_to @criminal, notice: 'Criminal was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @criminal.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /criminals/1
  # DELETE /criminals/1.json
  def destroy
    @criminal = Criminal.find(params[:id])
    @criminal.destroy

    respond_to do |format|
      format.html {}
      format.json { head :ok }
    end
  end
  private
  def sort_column
    Criminal.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def info
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  respond_to :html
  before_filter :authenticate_user!
  helper_method :sort_column , :sort_direction
  def index
    @results = Result.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @results }
    end
  end
  def show
    @result = Result.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @result }
    end
  end
  private
  def sort_column
    Result.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end
end

app/helpers/criminals_helper.rb
module CriminalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/criminals/_form.html.erb
<%= form_for @criminal, :html => {:multipart => true} do |f| %>
<% if @criminal.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@criminal.errors.count, "error") %> prohibited this criminal from being saved:</h2>

  <ul>
    <% @criminal.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div id="upload">
  <%= f.label :photo ,"Select the Photo " %>
  <%= f.file_field :photo %>
</div>
<div class="actions">
  <%= f.submit "Submit" %>
</div>
<% end %>

app/views/criminals/edit.html.erb
<h1>Editing criminal</h1>

<%= render 'form' %>

<%= link_to 'Show', @criminal %> |
<%= link_to 'Back', criminals_path %>

app/views/criminals/index.html.erb
<%=stylesheet_link_tag("/stylesheet/demo_table_jui.css")%>
<div id ='criminal_index'>
<h1>Criminals Info</h1>
<%= form_tag criminals_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<table id='criminal_index_table' class="zebra-striped bordered-table dataTable">
  <tr>
    <th><%= sortable "name" %></th>
    <th>Gender</th>
    <th><%= sortable "Age" %></th>
    <th>Race</th>
    <th>Eye color</th>
    <th>Hair color</th>
    <th>Photo</th>
    <th>Additional info</th>
    <th></th>
    <th></th>
  </tr>

<% @criminals.each do |criminal| %>
  <tr>
    <td><%= criminal.name %></td>
    <td><%= criminal.gender %></td>
    <td><%= criminal.age %></td>
    <td><%= criminal.race %></td>
    <td><%= criminal.eye_color %></td>
    <td><%= criminal.hair_color %></td>
    <td><%= image_tag criminal.photo_url.to_s %></td>
    <td><%= criminal.additional_info %></td>
    <td><%= link_to 'Profile', criminal %></td>
    <td><%= link_to 'Remove', criminal, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<br />
</div>

app/views/criminals/new.html.erb
<h1>Upload the photo</h1>
<%= render 'form' %>
<%= link_to 'Back', criminals_path %>

app/views/criminals/show.html.erb
<div id='criminal-photo'>
<p>
  <%= image_tag @criminal.photo_url.to_s ,:class=>"thumbnail"%>
</p>
</div>
<%= link_to 'Back', results_path %>

app/views/home/index.html.erb
<% if user_signed_in? %>

  <% else %>
  <p><%= link_to 'sign in', new_user_session_path %> </p>
<% end %> `

app/views/layouts/_footer.html.erb
<footer>
  <p> Copyright &copy; 2012 Criminal Investigation </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <hgroup>
    <div id='logo'>
    <ul id="topnav" class="clearfix">
    <li><a href="../results">Home</a></li>
    <li><a href="#">Most Wanted</a></li>
    <li><a href="../criminals/new">Upload</a></li>
    <li><% if user_signed_in?%>
        <div id = "welcome_message"><%=current_user.email%>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %><% end %></a></li>
    </ul>
   </div>
  </hgroup>
</header>

app/views/layouts/_tabs.html.erb
 <% if user_signed_in? %>
    <ul class="tabs">
    <li><a href="../criminals">Home</a></li>
    <li><a href="../criminals/new">Upload Photo</a></li>
    </ul>
<% else %>
    <p>You are not authorized to enter the site </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Criminal Investigation</title>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag    "bootstrap" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <header>
  <%= render 'layouts/header' %>
  </header>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  </div>
</body>
<%= render 'layouts/footer' %>
</div>
</html>

app/views/results/index.html.erb
<%=stylesheet_link_tag("/stylesheet/demo_table_jui.css")%>
<div id ='result_index'>
<h1>Criminals Info</h1>
<table id='result_index_table' class="dataTable">
  <thead>
  <tr>
    <th>Name</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Race</th>
    <th>Eye color</th>
    <th>Hair color</th>
    <th>Additional info</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
<% @results.each do |result| %>
  <tr>
    <td><%= link_to result.name, result %></td>
    <td><%= result.gender %></td>
    <td><%= result.age %></td>
    <td><%= result.race %></td>
    <td><%= result.eye_color %></td>
    <td><%= result.hair_color %></td>
    <td><%= result.additional_info %></td>
    <td><%= link_to 'Profile', result %></td>
  </tr>
<% end %>
 </tbody>
</table>

<br />
</div>

app/views/results/show.html.erb
<div id ="result-profile">
<div id='result-photo'>
  <p>
    <%= image_tag @result.photo ,:class=>"thumbnail"%>
  </p>
</div>
<div id ="result-info">
<p>
  <b>Name:</b>
  <%= @result.name %>
</p>

<p>
  <b>Gender:</b>
  <%= @result.gender %>
</p>

<p>
  <b>Age:</b>
  <%= @result.age %>
</p>

<p>
  <b>Race:</b>
  <%= @result.race %>
</p>

<p>
  <b>Eye color:</b>
  <%= @result.eye_color %>
</p>

<p>
  <b>Hair color:</b>
  <%= @result.hair_color %>
</p>

<p>
  <b>Additional info:</b>
  <%= @result.additional_info %>
</p>
</div><br/>
</div>

<%= link_to 'Back', results_path %>